name: Org Usage Stats

on:
  schedule:
    - cron: '0 0 * * 4'  # Run every Thursday at midnight UTC
  workflow_dispatch:

jobs:
  search-mesh-usage:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        working-directory: scripts/sidan-gov
      
      - name: Generate Current Stats
        run: npm run generate-org-stats
        working-directory: scripts/sidan-gov
        
      - name: Generate Yearly Stats
        run: npm run generate-yearly-stats
        working-directory: scripts/sidan-gov
        
      - name: Check for changes
        id: git-check
        run: |
          git status --porcelain
          echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit files
        if: steps.git-check.outputs.changes > 0
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add gov-updates/org-stats/*.json
          git commit -m "Update Org usage statistics"
          
      - name: Push changes
        if: steps.git-check.outputs.changes > 0
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
